"""
Norwegian Blue Carbon: management priority by pressure and protection.

Single panel — carbon stock (Gg C) in each management class, grouped by habitat
(kelp / seagrass), with the class definitions annotated. Each region-habitat unit
is assigned to one class from two thresholds (below).

Management classes are defined by two thresholds applied to the region-habitat units:
  Pressure threshold  = within-dataset median (relative comparison)
  MPA adequacy        = ≥10% of habitat area inside a strict marine MPA (policy benchmark)

  SAFEGUARD      low pressure + adequate MPA  → maintain and monitor
  TRIAGE         high pressure + adequate MPA → enforce existing protection, reduce impacts
  MONITOR        low pressure + inadequate MPA → pre-emptive designation before threats arrive
  URGENT PROTECT high pressure + inadequate MPA → designate protection now

Input:
  data/processed/regional_priority_metrics.csv  (generated by figure_priority_quadrant.py)

Output:
  figures/figure_carbon_profile.png / .pdf
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PROC = ROOT / "data" / "processed"
FIG = ROOT / "figures"
FIG.mkdir(exist_ok=True)

METRICS_PATH = PROC / "regional_priority_metrics.csv"

REGION_ORDER = ["Barents Sea", "Norwegian Sea", "Skagerrak"]

HABITAT_COLOR = {
    "macroalgae": "#2c6e49",
    "seagrass":   "#74c476",
}
HABITAT_LABEL = {"macroalgae": "Kelp", "seagrass": "Seagrass"}

QUADRANT_COLORS = {
    "SAFEGUARD":      "#bbf7d0",
    "URGENT PROTECT": "#fecaca",
    "MONITOR":        "#e2e8f0",
    "TRIAGE":         "#fde68a",
}
QUADRANT_DEFS = {
    "SAFEGUARD":      "Low pressure\n≥10% MPA\n→ maintain & monitor",
    "TRIAGE":         "High pressure\n≥10% MPA\n→ enforce existing\nprotection",
    "MONITOR":        "Low pressure\n<10% MPA\n→ add protection to\nsafeguard carbon",
    "URGENT PROTECT": "High pressure\n<10% MPA\n→ designate\nprotection now",
}

# Human-readable x-axis labels (display names separate from internal category keys)
QUADRANT_DISPLAY = {
    "SAFEGUARD":      "Continue\nMonitoring",
    "URGENT PROTECT": "URGENT\nPROTECT",
    "MONITOR":        "High\nPreservation\nValue",
    "TRIAGE":         "TRIAGE",
}

MPA_THRESHOLD_PCT = 10.0


def load_data() -> pd.DataFrame:
    df = pd.read_csv(METRICS_PATH)
    return df[df["canonical_region"].isin(REGION_ORDER)].copy()


def build_pressure_index(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    components = ["dredging_per_km2", "akvakultur_per_km2", "platforms_10km"]
    for col in components:
        vmin, vmax = df[col].min(), df[col].max()
        df[f"{col}_n"] = (df[col] - vmin) / (vmax - vmin) if vmax > vmin else 0.5
    df["pressure_index"] = df[[f"{c}_n" for c in components]].mean(axis=1)
    return df


def classify_quadrant(pressure: float, mpa_pct: float, pressure_threshold: float) -> str:
    high_p = pressure > pressure_threshold
    high_m = mpa_pct >= MPA_THRESHOLD_PCT
    if not high_p and high_m:
        return "SAFEGUARD"
    elif high_p and high_m:
        return "TRIAGE"
    elif not high_p and not high_m:
        return "MONITOR"
    else:
        return "URGENT PROTECT"


def panel_b_carbon_by_class(ax, df: pd.DataFrame) -> None:
    quadrant_order = ["SAFEGUARD", "URGENT PROTECT", "MONITOR", "TRIAGE"]
    pivot = (
        df.groupby(["quadrant", "ecosystem"])["stock_GgC"]
        .sum()
        .unstack(fill_value=0)
        .reindex(quadrant_order, fill_value=0)
    )
    for eco in ["macroalgae", "seagrass"]:
        if eco not in pivot.columns:
            pivot[eco] = 0.0

    grand_total = float(pivot.values.sum())
    ymax = float(pivot.sum(axis=1).max())
    x = np.arange(len(quadrant_order))
    bw = 0.36

    # Background shading per management class
    for xi, q in zip(x, quadrant_order):
        ax.axvspan(xi - 0.5, xi + 0.5, color=QUADRANT_COLORS[q], alpha=0.5, zorder=0)

    for i, eco in enumerate(["macroalgae", "seagrass"]):
        vals = pivot[eco].values
        offset = (i - 0.5) * bw
        bars = ax.bar(
            x + offset, vals, bw,
            label=HABITAT_LABEL[eco],
            color=HABITAT_COLOR[eco],
            edgecolor="black", linewidth=0.7, zorder=3,
        )
        for bar, v in zip(bars, vals):
            if v > 1:
                ax.text(bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + ymax * 0.012, f"{v:,.0f}",
                        ha="center", va="bottom", fontsize=9, fontweight="bold")

    # Class total + share of national stock above each group
    for xi, q in zip(x, quadrant_order):
        total = float(pivot.loc[q].sum())
        if total > 1:
            ax.text(xi, total + ymax * 0.05,
                    f"Σ {total:,.0f} Gg C\n{total / grand_total * 100:.0f}% of stock",
                    ha="center", va="bottom", fontsize=8.5,
                    color="#222", fontweight="bold")

    # Class name + definition below the axis
    ax.set_xticks([])
    for xi, q in zip(x, quadrant_order):
        ax.text(xi, -ymax * 0.04, QUADRANT_DISPLAY[q].replace("\n", " "),
                ha="center", va="top", fontsize=10.5, fontweight="bold", color="#222")
        ax.text(xi, -ymax * 0.13, QUADRANT_DEFS[q],
                ha="center", va="top", fontsize=8, color="#555", style="italic")

    ax.set_ylabel("Carbon stock at stake (Gg C)", fontsize=10.5)
    ax.set_title("Carbon at Stake by Management Class", loc="left",
                 fontweight="bold", fontsize=13)
    ax.legend(fontsize=9.5, frameon=False, loc="upper right")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_ylim(-ymax * 0.50, ymax * 1.24)

    # Thresholds key (upper-left, over the low SAFEGUARD column)
    ax.text(0.015, 0.97,
            "Class thresholds\n"
            "• Pressure: high = above national median\n"
            "• Protection: adequate = ≥10% in strict MPA",
            transform=ax.transAxes, va="top", ha="left", fontsize=8, color="#333",
            bbox=dict(facecolor="white", edgecolor="#ccc",
                      boxstyle="round,pad=0.4", linewidth=0.6), zorder=5)


def render(df: pd.DataFrame) -> Path:
    fig = plt.figure(figsize=(10.5, 7.5))
    ax = fig.add_axes([0.10, 0.16, 0.86, 0.72])
    panel_b_carbon_by_class(ax, df)

    fig.suptitle(
        "Norwegian Blue Carbon: Management Priority by Pressure and Protection",
        fontsize=14, fontweight="bold", y=0.97,
    )
    fig.text(
        0.5, 0.02,
        "Each region–habitat unit (kelp and seagrass × Barents Sea, Norwegian Sea, Skagerrak + Oslofjord) is "
        "assigned to a management class from two thresholds: anthropogenic pressure (high if above the national "
        "median) and protection (adequate if ≥10% of habitat area lies in a strict marine protected area). "
        "Bars show carbon stock (Gg C) in each class. Kelp applies a national mean density (Gundersen 2021) to "
        "mapped regional area; seagrass uses regional field measurements (Gagnon 2024).",
        fontsize=7.5, color="#666", ha="center", style="italic",
    )

    out_png = FIG / "figure_carbon_profile.png"
    out_pdf = FIG / "figure_carbon_profile.pdf"
    fig.savefig(out_png, dpi=200, bbox_inches="tight")
    fig.savefig(out_pdf, bbox_inches="tight")
    plt.close(fig)
    return out_png


def main() -> None:
    df = load_data()
    df = build_pressure_index(df)
    pressure_threshold = df["pressure_index"].median()
    df["quadrant"] = df.apply(
        lambda r: classify_quadrant(
            r["pressure_index"], r["percent_habitat_in_mpa"], pressure_threshold
        ),
        axis=1,
    )
    out = render(df)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
