"""
Norwegian Carbon Profile: regional stocks and management priority.

Panel A  Regional carbon stock (GgC) — kelp + seagrass stacked bars by region
Panel B  Carbon at stake by management class — total GgC in each action category,
         grouped by habitat, with management-class definitions annotated

Management classes are defined by two thresholds applied to the region-habitat units:
  Pressure threshold  = within-dataset median (relative comparison)
  MPA adequacy        = ≥10% of habitat area inside a strict marine MPA (policy benchmark)

  SAFEGUARD      low pressure + adequate MPA  → maintain and monitor
  URGENT PROTECT high pressure + adequate MPA → enforce protection, reduce impacts
  MONITOR        low pressure + inadequate MPA → pre-emptive designation before threats arrive
  TRIAGE         high pressure + inadequate MPA → immediate intervention required

Input:
  data/processed/regional_priority_metrics.csv  (generated by figure_priority_quadrant.py)

Output:
  figures/figure_carbon_profile.png / .pdf
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.gridspec import GridSpec

ROOT = Path(__file__).resolve().parent.parent
PROC = ROOT / "data" / "processed"
FIG = ROOT / "figures"
FIG.mkdir(exist_ok=True)

METRICS_PATH = PROC / "regional_priority_metrics.csv"

REGION_ORDER = ["Barents Sea", "Norwegian Sea", "Skagerrak"]

HABITAT_COLOR = {
    "macroalgae": "#2c6e49",
    "seagrass":   "#74c476",
}
HABITAT_LABEL = {"macroalgae": "Kelp", "seagrass": "Seagrass"}

QUADRANT_COLORS = {
    "SAFEGUARD":      "#bbf7d0",
    "URGENT PROTECT": "#fecaca",
    "MONITOR":        "#e2e8f0",
    "TRIAGE":         "#fde68a",
}
QUADRANT_DEFS = {
    "SAFEGUARD":      "Low pressure\n≥10% MPA\n→ maintain & monitor",
    "URGENT PROTECT": "High pressure\n≥10% MPA\n→ enforce protection",
    "MONITOR":        "Low pressure\n<10% MPA\n→ add protection to\nsafeguard carbon",
    "TRIAGE":         "High pressure\n<10% MPA\n→ immediate intervention",
}

# Human-readable x-axis labels (display names separate from internal category keys)
QUADRANT_DISPLAY = {
    "SAFEGUARD":      "Continue\nMonitoring",
    "URGENT PROTECT": "URGENT\nPROTECT",
    "MONITOR":        "High\nPreservation\nValue",
    "TRIAGE":         "TRIAGE",
}

MPA_THRESHOLD_PCT = 10.0


def load_data() -> pd.DataFrame:
    df = pd.read_csv(METRICS_PATH)
    return df[df["canonical_region"].isin(REGION_ORDER)].copy()


def build_pressure_index(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    components = ["dredging_per_km2", "akvakultur_per_km2", "platforms_10km"]
    for col in components:
        vmin, vmax = df[col].min(), df[col].max()
        df[f"{col}_n"] = (df[col] - vmin) / (vmax - vmin) if vmax > vmin else 0.5
    df["pressure_index"] = df[[f"{c}_n" for c in components]].mean(axis=1)
    return df


def classify_quadrant(pressure: float, mpa_pct: float, pressure_threshold: float) -> str:
    high_p = pressure > pressure_threshold
    high_m = mpa_pct >= MPA_THRESHOLD_PCT
    if not high_p and high_m:
        return "SAFEGUARD"
    elif high_p and high_m:
        return "URGENT PROTECT"
    elif not high_p and not high_m:
        return "MONITOR"
    else:
        return "TRIAGE"


def panel_a_stocks(ax, df: pd.DataFrame) -> None:
    pivot = (
        df.pivot(index="canonical_region", columns="ecosystem", values="stock_GgC")
        .reindex(REGION_ORDER)
    )
    x = np.arange(len(pivot))
    kelp_vals = pivot["macroalgae"].values
    sg_vals   = pivot["seagrass"].values
    bw = 0.6

    ax.bar(x, kelp_vals, bw, label="Kelp",
           color=HABITAT_COLOR["macroalgae"], edgecolor="black", linewidth=0.6, hatch="//")
    ax.bar(x, sg_vals, bw, bottom=kelp_vals, label="Seagrass",
           color=HABITAT_COLOR["seagrass"], edgecolor="black", linewidth=0.6)

    region_short = {
        "Barents Sea":    "Barents Sea",
        "Norwegian Sea":  "Norwegian Sea",
        "Skagerrak":      "Skagerrak\n(+ Oslofjord)",
    }
    ax.set_xticks(x)
    ax.set_xticklabels([region_short[r] for r in pivot.index], fontsize=9)
    ax.set_ylabel("Carbon stock (Gg C)", fontsize=9.5)
    ax.set_title("A.  Regional Carbon Stock", loc="left", fontweight="bold", fontsize=12)
    ax.legend(loc="upper right", frameon=False, fontsize=9)

    ymax = (kelp_vals + sg_vals).max()
    for xi, kv, sv in zip(x, kelp_vals, sg_vals):
        ax.text(xi, kv + sv + ymax * 0.03, f"{kv + sv:.0f}",
                ha="center", fontsize=9, fontweight="bold")
        if sv > ymax * 0.04:
            ax.text(xi, kv + sv / 2, f"{sv:.0f}",
                    ha="center", va="center", fontsize=8, color="white")

    ax.set_ylim(0, ymax * 1.18)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def panel_b_carbon_by_class(ax, df: pd.DataFrame) -> None:
    quadrant_order = ["SAFEGUARD", "URGENT PROTECT", "MONITOR", "TRIAGE"]
    pivot = (
        df.groupby(["quadrant", "ecosystem"])["stock_GgC"]
        .sum()
        .unstack(fill_value=0)
        .reindex(quadrant_order, fill_value=0)
    )
    for eco in ["macroalgae", "seagrass"]:
        if eco not in pivot.columns:
            pivot[eco] = 0.0

    x = np.arange(len(quadrant_order))
    bw = 0.36

    for i, eco in enumerate(["macroalgae", "seagrass"]):
        vals = pivot[eco].values
        offset = (i - 0.5) * bw
        bars = ax.bar(
            x + offset, vals, bw,
            label=HABITAT_LABEL[eco],
            color=HABITAT_COLOR[eco],
            edgecolor="black", linewidth=0.7,
        )
        for bar, v in zip(bars, vals):
            if v > 1:
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + 12,
                    f"{v:.0f}",
                    ha="center", va="bottom", fontsize=8.5, fontweight="bold",
                )

    # Background shading per quadrant
    for xi, q in zip(x, quadrant_order):
        ax.axvspan(xi - 0.48, xi + 0.48, color=QUADRANT_COLORS[q], alpha=0.55, zorder=0)

    ax.set_xticks(x)
    ax.set_xticklabels([QUADRANT_DISPLAY[q] for q in quadrant_order],
                       fontsize=9, fontweight="bold")

    ymax = pivot.values.max() * 1.25
    ax.set_ylim(0, max(ymax, 100))
    ax.set_ylabel("Carbon stock at stake (Gg C)", fontsize=9.5)
    ax.set_title("B.  Carbon at Stake by Management Class", loc="left",
                 fontweight="bold", fontsize=12)
    ax.legend(fontsize=9, frameon=False, loc="upper right")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    # Totals above each group
    for xi, q in zip(x, quadrant_order):
        if q not in pivot.index:
            continue
        total = pivot.loc[q].sum()
        if total > 1 and (pivot.loc[q] > 0).sum() > 1:
            ax.text(xi, total + ymax * 0.02, f"Σ {total:.0f}",
                    ha="center", va="bottom", fontsize=8,
                    color="#444", style="italic", fontweight="bold")

    # Definition annotations below each category bar group
    for xi, q in zip(x, quadrant_order):
        ax.text(xi, -ymax * 0.04, QUADRANT_DEFS[q],
                ha="center", va="top", fontsize=7,
                color="#444", style="italic",
                transform=ax.transData)

    ax.set_ylim(-ymax * 0.38, max(ymax, 100))


def render(df: pd.DataFrame) -> Path:
    fig = plt.figure(figsize=(13, 7))
    gs = GridSpec(1, 2, figure=fig, width_ratios=[1.0, 1.3],
                  wspace=0.38, left=0.08, right=0.97, top=0.90, bottom=0.10)
    ax_a = fig.add_subplot(gs[0, 0])
    ax_b = fig.add_subplot(gs[0, 1])

    panel_a_stocks(ax_a, df)
    panel_b_carbon_by_class(ax_b, df)

    fig.suptitle(
        "Norwegian Blue Carbon Profile: Regional Stocks and Management Priority",
        fontsize=14, fontweight="bold", y=0.98,
    )
    fig.text(
        0.5, 0.006,
        "Panel A: Total carbon stock (Gg C) by region; kelp uses national mean density (Gundersen 2021), "
        "seagrass uses regional mean density (Gagnon 2024). Hatching = kelp (equal-density assumption). "
        "Panel B: Carbon in each management class. Pressure threshold = within-dataset median; "
        "MPA adequacy = 10% (policy benchmark). Values in Gg C.",
        fontsize=7.5, color="#666", ha="center", style="italic",
    )

    out_png = FIG / "figure_carbon_profile.png"
    out_pdf = FIG / "figure_carbon_profile.pdf"
    fig.savefig(out_png, dpi=200, bbox_inches="tight")
    fig.savefig(out_pdf, bbox_inches="tight")
    plt.close(fig)
    return out_png


def main() -> None:
    df = load_data()
    df = build_pressure_index(df)
    pressure_threshold = df["pressure_index"].median()
    df["quadrant"] = df.apply(
        lambda r: classify_quadrant(
            r["pressure_index"], r["percent_habitat_in_mpa"], pressure_threshold
        ),
        axis=1,
    )
    out = render(df)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
